/*
 * generated by Xtext
 */
package ooi.coi.bspl.ui.contentassist;

/**
 * see
 * http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on
 * how to customize content assistant
 */
public class BSPLProposalProvider extends AbstractBSPLProposalProvider {

}
