/*
* generated by Xtext
*/
package ooi.coi.bspl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class BSPLOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
