/*
 * generated by Xtext
 */
package ooi.bspl;

import ooi.bspl.scoping.BSPLScopeProvider;
import org.eclipse.xtext.scoping.IScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BSPLRuntimeModule extends ooi.bspl.AbstractBSPLRuntimeModule {

	//Cloned by MPS from the DomainModel example
	@Override
	public Class<? extends IScopeProvider> bindIScopeProvider() {
		return BSPLScopeProvider.class;
	}

}
