/*
 * generated by Xtext
 */
package ooi.coi.bspl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BSPLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ooi.coi.bspl.ui.internal.BSPLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ooi.coi.bspl.ui.internal.BSPLActivator.getInstance().getInjector("ooi.coi.bspl.BSPL");
	}
	
}
