/*
* generated by Xtext
*/
package ooi.coi.bspl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class BSPLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return ooi.coi.bspl.ui.internal.BSPLActivator.getInstance().getInjector("ooi.coi.bspl.BSPL");
	}
	
}
