CREATE DATABASE IF NOT EXISTS EPU;
USE EPU;
CREATE TABLE IF NOT EXISTS EPU.launch (binding varchar(32) NOT NULL,CONSTRAINT PK_launch PRIMARY KEY (binding));
CREATE TABLE IF NOT EXISTS EPU.done (binding varchar(32) NOT NULL,confirm varchar(32) NOT NULL,CONSTRAINT PK_done PRIMARY KEY (binding));
