/*
* generated by Xtext
*/
package ooi.bspl.ui.contentassist;

import ooi.bspl.ui.contentassist.AbstractBSPLProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class BSPLProposalProvider extends AbstractBSPLProposalProvider {

}
