/*
 * generated by Xtext
 */
package ooi.bspl.ui;

import org.eclipse.jface.text.IAutoEditStrategy;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import ooi.bspl.ui.autoedit.BSPLFantasticAutoEditStrategy;
import ooi.bspl.ui.linking.BSPLLinkingDiagnosticMessageProvider;
import ooi.bspl.ui.navigation.BSPLHyperlinkHelper;
import org.eclipse.xtext.linking.ILinkingDiagnosticMessageProvider;
import org.eclipse.xtext.ui.editor.hyperlinking.IHyperlinkHelper;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BSPLUiModule extends ooi.bspl.ui.AbstractBSPLUiModule {
	public BSPLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends ILinkingDiagnosticMessageProvider> bindILinkingDiagnosticMessageProvider() {
		return BSPLLinkingDiagnosticMessageProvider.class;
	}
	
	public Class<? extends IHyperlinkHelper> bindIHyperlinkHelper() {
		return BSPLHyperlinkHelper.class;
	}
	
	public Class<? extends IAutoEditStrategy> bindIAutoEditStrategy() {
		return BSPLFantasticAutoEditStrategy.class;
	}

}
