<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bSPL"
    nsURI="http://www.bspl.ooi.org/BSPL" nsPrefix="bSPL">
  <eClassifiers xsi:type="ecore:EClass" name="BSPL">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="junkProtocol" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="junkRole" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1"
        eType="#//Role" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="junkPub" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="publicParams" upperBound="-1"
        eType="#//ParamDecl" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="junkPriv" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="privateParams" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="references" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParamDecl">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="adornment" eType="#//kAdornment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="param" eType="#//Parameter"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParamRef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="adornment" eType="#//kAdornment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="param" eType="#//Parameter"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Message">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sender" eType="#//Role"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="receiver" eType="#//Role"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="#//ParamRef" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="#//BSPL"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" unique="false" upperBound="-1"
        eType="#//Role"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="#//ParamRef" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="kAdornment">
    <eLiterals name="in" literal="in"/>
    <eLiterals name="out" value="1" literal="out"/>
    <eLiterals name="io" value="2" literal="io"/>
    <eLiterals name="nil" value="3" literal="nil"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="kPROTOCOL">
    <eLiterals name="protocol" literal="protocol"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="kROLE">
    <eLiterals name="role" literal="role"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="kPARAMETER">
    <eLiterals name="parameter" literal="parameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="kPRIVATE">
    <eLiterals name="private" literal="private"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="kKEY">
    <eLiterals name="key" literal="key"/>
  </eClassifiers>
</ecore:EPackage>
